// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "jQuery"], function(Console, $) {
    "use strict";
    return function($scope, DiagnosticWordsService) {
      var game, goLevel, level;
      game = $('#game');
      level = 0;
      $scope.$parent.loadDiagnostic = function() {
        var diagnostic_data;
        Console.group("Diagnostic");
        diagnostic_data = {
          lang_dir: LANG_DIR,
          profile: level + 1
        };
        Console.info("Loading: ", diagnostic_data);
        game.addClass("loading");
        return DiagnosticWordsService.get(diagnostic_data, function(response) {
          game.removeClass("loading");
          $scope.$root.diagnostic.response = response;
          Console.info("Data loaded: ", response);
          Console.groupEnd();
          return $scope.goScreen("diagnostic-games-intro");
        });
      };
      goLevel = function(l) {
        Console.info("Set diagnostic level " + l);
        return $scope.$parent.level = level = l;
      };
      $scope.$parent.prevLevel = function() {
        return goLevel((3 + level - 1) % 3);
      };
      $scope.$parent.nextLevel = function() {
        return goLevel((3 + level + 1) % 3);
      };
      return goLevel(0);
    };
  });

}).call(this);
