// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "jQuery"], function(Console, $) {
    "use strict";
    return function($scope, DiagnosticWordsService) {
      var game;
      game = $('#game');
      return $scope.$parent.loadDiagnostic = function() {
        var diagnostic_data;
        Console.group("Diagnostic");
        diagnostic_data = {
          lang_dir: LANG_DIR,
          profile: $scope.$root.diagnostic.level + 1
        };
        Console.info("Loading: ", diagnostic_data);
        game.addClass("loading");
        return DiagnosticWordsService.get(diagnostic_data, function(response) {
          var diagnosticWords;
          game.removeClass("loading");
          diagnosticWords = response;
          Console.info("Data loaded: ", response);
          Console.groupEnd();
          return $scope.goScreen("diagnostic-games-intro");
        });
      };
    };
  });

}).call(this);
