// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "Underscore", "jQuery"], function(Console, _, $) {
    "use strict";
    return function($scope, GamesService, games) {
      var game;
      game = $('#game');
      $scope.$parent.goGames = function() {
        Console.group("User games");
        game.addClass("loading");
        Console.info("Loading");
        return GamesService.get({
          lang_dir: LANG_DIR
        }, function(response) {
          game.removeClass("loading");
          Console.info("Data loaded: ", response);
          Console.groupEnd();
          $scope.$parent.gameList = _.map(response.Games, function(game) {
            game.Game.type = games.id(parseInt(game.Game.id)).type;
            return game.Game;
          });
          $scope.gameIndex = 0;
          $scope.$apply();
          return $scope.goScreen("user-games");
        });
      };
      $scope.$parent.prevGame = function() {
        return $scope.$parent.gameIndex = $scope.$parent.gameIndex - 1;
      };
      return $scope.$parent.nextGame = function() {
        return $scope.$parent.gameIndex = $scope.$parent.gameIndex + 1;
      };
    };
  });

}).call(this);
