// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "jQuery", "Underscore"], function(Console, $, _) {
    "use strict";

    var controller;
    Console.group("Entering AppController module.");
    controller = function($scope, user, games) {
      var game, gamehelpscreen, selector;
      gamehelpscreen = $("#game-help-screen");
      game = $("#game");
      selector = void 0;
      $scope.$root.audio = true;
      $scope.user = user;
      $scope.$root.lifes = false;
      $scope.$root.diagnostic = {
        level: 0,
        gameIndex: 0,
        points: 0,
        timeout: false,
        response: {
          game: []
        },
        finished: function() {
          return this.gameIndex >= this.gameTotal() || this.timeout || $scope.$root.lifes === 0;
        },
        gameTotal: function() {
          return this.response.game.length;
        },
        gameData: function() {
          if (this.finished() || !this.response.game.length) {
            return {};
          }
          return this.response.game[this.gameIndex];
        },
        game: function() {
          var id;
          id = this.gameData().gid;
          if (id) {
            return games.id(id);
          }
        }
      };
      $scope.support = {
        effects: Modernizr.cssanimations && Modernizr.csstransitions
      };
      $scope.$root.effects = EFFECTS && $scope.support.effects;
      Console.info("Support", $scope.support);
      $scope.showHelp = function() {
        gamehelpscreen.click(function() {
          return game.removeClass("help");
        });
        game.addClass("help");
        if (game.hasClass("play")) {
          selector = $("#game-header [data-help], #game .game.active [data-help]");
        } else {
          selector = $("#top-bar [data-help], #game .screen.active [data-help]");
        }
        gamehelpscreen.empty();
        return selector.each(function() {
          var height, helptext, left, padding, pos, position, position_rel, top, width, _this;
          _this = $(this);
          helptext = _this.data("help");
          position = _this.offset();
          position_rel = game.offset();
          pos = $("<div class=\"help-position\"><span class=\"help-text\"/></div>");
          pos.children().text(helptext).addClass(_this.data("help-position") || "tr");
          padding = 0;
          left = position.left - position_rel.left - padding;
          top = position.top - position_rel.top - padding;
          width = _this.outerWidth();
          height = _this.outerHeight();
          return pos.appendTo(gamehelpscreen).css({
            left: left,
            top: top,
            width: width,
            height: height,
            padding: padding
          });
        });
      };
      $scope.toggleSettings = function() {
        if (!$scope.goScreen("settings")) {
          return $scope.backScreen();
        }
      };
      return $scope.toggleAudio = function() {
        return $scope.$root.audio = !$scope.$root.audio;
      };
    };
    controller.$inject = ["$scope", "user", "games"];
    return controller;
  });

}).call(this);
