// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "jQuery"], function(Console, $) {
    "use strict";
    return function($scope, $element, user, UserWordStatus) {
      return $scope.$parent.openWord = function() {
        var _this = this;
        Console.info('****************** OPENED WORD', this);
        this.$parent.openedWord = this.word.id !== this.openedWord ? this.word.id : false;
        if (!this.loaded) {
          return UserWordStatus.get({
            word: this.word.id
          }, function(response) {
            _this.loaded = true;
            return _this.data = response;
          });
        }
      };
    };
  });

}).call(this);
