// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "jQuery"], function(Console, $) {
    "use strict";
    return function($scope, $element, user) {
      var exit;
      exit = function() {
        return $scope.exitGame();
      };
      $scope.$parent.goGameMenu = function() {
        exit();
        return $scope.hidePopup();
      };
      $scope.$parent.checkWords = function() {
        return $scope.showPopup('postgame-words');
      };
      return this.onHide = function() {
        return exit();
      };
    };
  });

}).call(this);
