// Generated by CoffeeScript 1.3.3
/* ParticleAttraction Behaviour
*/

var ParticleAttraction,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

ParticleAttraction = (function(_super) {

  __extends(ParticleAttraction, _super);

  function ParticleAttraction(target, radius, strength) {
    this.target = target;
    this.radius = radius != null ? radius : 1000;
    this.strength = strength != null ? strength : 100.0;
    this._delta = new Vector();
    this.setRadius(this.radius);
    ParticleAttraction.__super__.constructor.apply(this, arguments);
  }

  /* Sets the effective radius of the bahavious.
  */


  ParticleAttraction.prototype.setRadius = function(radius) {
    this.radius = radius;
    return this.radiusSq = radius * radius;
  };

  ParticleAttraction.prototype.apply = function(p, dt, index) {
    var distSq;
    (this._delta.copy(this.target.pos)).sub(p.pos);
    distSq = this._delta.magSq();
    if (distSq < this.radiusSq && distSq > 0.000001) {
      this._delta.norm().scale(1.0 - distSq / this.radiusSq);
      return p.acc.add(this._delta.scale(this.strength));
    }
  };

  return ParticleAttraction;

})(Behaviour);
