// Generated by CoffeeScript 1.3.3
(function() {

  define(["lib/console/console-min"], function() {
    debug.group("Entering Console module.");
    debug.info("console: ", debug);
    debug.groupEnd();
    return debug;
  });

}).call(this);
