// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "lib/soundmanager2/soundmanager2-jsmin"], function(Console) {
    var soundManager;
    Console.group("Entering SoundManager module.");
    Console.info("SoundManager: ", SoundManager);
    soundManager = new SoundManager();
    Console.groupEnd();
    return soundManager;
  });

}).call(this);
