// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "lib/underscore/underscore-min"], function(Console) {
    Console.group("Entering Underscore module.");
    Console.info("Underscore: ", _);
    Console.groupEnd();
    return _;
  });

}).call(this);
