// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console"], function(Console) {
    "use strict";
    Console.group("Entering dialog directive module.");
    Console.groupEnd();
    return function() {
      return {
        require: "^screen",
        restrict: "E",
        transclude: true,
        scope: {},
        link: function(scope, element, attrs, screenCtrl) {
          return screenCtrl.addDialog(scope, element, attrs);
        },
        template: "<div class=\"dialog\" ng-class=\"{show:show}\" ng-transclude></div>",
        replace: true
      };
    };
  });

}).call(this);
