// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "Angular"], function(Console, angular) {
    "use strict";
    Console.group("Entering game directive module.");
    Console.groupEnd();
    return function() {
      return {
        template: "<div class=\"popup\" ng-class=\"{active:active}\"><a ng-click=\"hidePopup()\" class=\"popup-close\"><i class=\"icon-remove\"></i></a><div ng-transclude></div></div>",
        require: "^popups",
        transclude: true,
        restrict: "E",
        scope: true,
        link: function(scope, element, attrs, popupsCtrl) {
          return popupsCtrl.addPopup(scope, element, attrs);
        },
        replace: true
      };
    };
  });

}).call(this);
