// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "jQuery"], function(Console, $) {
    "use strict";
    Console.group("Entering popups directive module.");
    Console.groupEnd();
    return function() {
      return {
        restrict: "E",
        transclude: true,
        scope: true,
        template: "<div class=\"popups\" ng-class=\"{active:active}\" ng-transclude></div>",
        replace: true,
        controller: function($scope, $element) {
          var hidePopup, opened_popups, popups;
          popups = {};
          opened_popups = [];
          $scope.$root.showPopup = function(name) {
            var el, last, last_popup;
            if (opened_popups.length) {
              last = opened_popups[opened_popups.length - 1];
              last_popup = popups[last];
              last_popup.scope.active = false;
              $(last_popup.element).hide();
            }
            $scope.active = true;
            popups[name].scope.active = true;
            el = $(popups[name].element);
            el.show();
            if ($scope.$root.effects) {
              el.keyframe("flipInPopup", 600);
            }
            opened_popups.push(name);
            return popups[name];
          };
          hidePopup = function() {
            var c, el, f, last, last_popup;
            Console.info("Hided Popup", opened_popups);
            if (!opened_popups.length) {
              Console.info("No popups");
              $scope.active = false;
              $scope.$apply();
            } else if (opened_popups.length === 1) {
              last = opened_popups.pop();
              el = $(popups[last].element);
              c = popups[last].controller;
              f = function() {
                if (c.onHide) {
                  c.onHide();
                }
                el.hide();
                return hidePopup();
              };
              if ($scope.$root.effects) {
                return el.keyframe("flipOutPopup", 600, f);
              } else {
                return f();
              }
            } else {
              last = opened_popups.pop();
              last_popup = popups[last];
              last_popup.scope.active = false;
              $(last_popup.element).hide();
              if (opened_popups.length) {
                last = opened_popups[opened_popups.length - 1];
                last_popup = popups[last];
                last_popup.scope.active = true;
                return $(last_popup.element).show();
              }
            }
          };
          $scope.$root.hidePopup = function() {
            return hidePopup();
          };
          return this.addPopup = function(scope, element, attrs) {
            var controller, name;
            name = attrs.popupId;
            controller = element.controller();
            Console.info("Registered popup " + name, scope, attrs, element, controller);
            return popups[name] = {
              scope: scope,
              controller: controller,
              element: element,
              attrs: attrs
            };
          };
        }
      };
    };
  });

}).call(this);
