// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "jQuery"], function(Console, $) {
    "use strict";
    Console.group("Entering game screens module.");
    Console.groupEnd();
    return function() {
      return {
        restrict: "E",
        transclude: true,
        controller: function($scope, $element) {
          var hided, historyScreens, moveBackground, screens, styles_in, styles_out, view;
          styles_out = {
            y: -50,
            opacity: 0
          };
          styles_in = {
            y: 0,
            opacity: 1
          };
          $('#top-bar').css(styles_out);
          screens = $scope.screens = {};
          historyScreens = [];
          hided = false;
          moveBackground = function(prev, next, left) {
            var direction, easing, showcss, time, trees_back, trees_front, x;
            direction = (left ? "+" : "-");
            trees_back = $("#game-background .trees-back");
            trees_front = $("#game-background .trees-front");
            trees_back.css("x", direction + "=200px");
            trees_front.css("x", direction + "=500px");
            if ($scope.$root.effects) {
              x = (left ? 1000 : -1000);
              time = 3000;
              easing = "cubic-bezier(0.530, 0.180, 0.425, 0.860)";
              screens[prev].element.removeClass("effects").children(":not(.dialog,.static)").css({
                transformOrigin: "bottom center"
              }).transit({
                x: x,
                opacity: .5,
                scale: .6
              }, time, easing);
              return screens[next].element.addClass("effects").children(":not(.dialog,.static)").css({
                x: -x,
                opacity: .5,
                scale: .6,
                transformOrigin: "bottom center"
              }).transit({
                x: 0,
                opacity: 1,
                scale: 1
              }, time, easing);
            } else {
              showcss = {
                x: 0,
                y: 0,
                opacity: 1
              };
              screens[next].element.removeClass("effects").children(":not(.dialog,.static)").css(showcss);
              return screens[prev].element.removeClass("effects").children(":not(.dialog,.static)").css(showcss);
            }
          };
          view = function(name, show, onfinish) {
            var screen;
            if (show) {
              Console.info("Viewing screen " + name);
            } else {
              Console.info("Hiding screen " + name);
            }
            screen = screens[name];
            hided = !show;
            if (show) {
              if ($scope.$root.effects) {
                $('#top-bar').css(styles_out).transit(styles_in, 600, function() {
                  return screen.scope.show(onfinish);
                });
              } else {
                screen.scope.show(onfinish);
              }
              historyScreens.push(name);
              $scope.title = screen.attrs.title || "None";
            } else {
              if ($scope.$root.effects) {
                screen.scope.hide(function() {
                  return $('#top-bar').css(styles_in).transit(styles_out, 600, onfinish);
                });
              } else {
                screen.scope.hide(onfinish);
              }
            }
            $scope.$apply();
            return screen;
          };
          $scope.$root.hideScreen = function(onfinish) {
            return view(historyScreens[historyScreens.length - 1], false, onfinish);
          };
          $scope.$root.goScreen = function(name) {
            var lastScreen, screen, _onfinish;
            lastScreen = historyScreens[historyScreens.length - 1];
            _onfinish = function() {
              return view(name, true);
            };
            if (!hided) {
              if (lastScreen === name) {
                return false;
              } else if (lastScreen) {
                screen = view(lastScreen, false, _onfinish);
                moveBackground(lastScreen, name);
              } else {
                _onfinish();
              }
            } else {
              _onfinish();
            }
            return true;
          };
          $scope.$root.backScreen = function() {
            var lastScreen, prevScreen;
            lastScreen = historyScreens.pop();
            prevScreen = historyScreens[historyScreens.length - 1];
            view(lastScreen, false, function() {
              var screen;
              return screen = view(prevScreen, true);
            });
            return moveBackground(lastScreen, prevScreen, true);
          };
          return this.addScreen = function(scope, element, attrs) {
            var name;
            name = attrs.screenId;
            Console.info("Registered screen " + name, scope, attrs);
            screens[name] = {
              scope: scope,
              element: element,
              attrs: attrs
            };
            if (attrs.hasOwnProperty("screenInit")) {
              $("#game-background .sun").one("animationend webkitAnimationEnd oanimationend MSAnimationEnd", function(e) {
                return $scope.goScreen(name);
              });
              if (!$scope.$root.effects) {
                return $("#game-background .sun").trigger("animationend");
              }
            }
          };
        },
        template: "<div class=\"screens\" ng-transclude></div>",
        replace: true
      };
    };
  });

}).call(this);
