// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console"], function(Console) {
    "use strict";

    var service;
    Console.group("Entering GameWords service module.");
    service = function($resource, $http) {
      var $get, ChallengeWords;
      ChallengeWords = $resource("" + API_BASE + "challenges/getChallengesWords/:lang_dir.json", {}, {
        get: {
          method: "GET"
        }
      });
      $get = ChallengeWords.get;
      ChallengeWords.get = function(data, f) {
        var _this = this;
        return $get(data, function(resp) {
          var d;
          d = resp.Words[0];
          d.gid = 8;
          return f.call(_this, d);
        });
      };
      return ChallengeWords;
    };
    Console.groupEnd();
    return service;
  });

}).call(this);
