// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console"], function(Console) {
    "use strict";

    var service;
    Console.group("Entering DiagnosticWords service module.");
    service = function($resource, $http) {
      return $resource("" + API_BASE + "diagnostics/getDiagnosticWordsBeta3/:lang_dir/:profile.json", {}, {
        update: {
          method: "PUT"
        },
        get: {
          method: "GET"
        }
      });
    };
    Console.groupEnd();
    return service;
  });

}).call(this);
