// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "Underscore"], function(Console, _) {
    "use strict";

    var service;
    Console.group("Entering Games service module.");
    service = function($resource, $http) {
      var $send, GamesPlayed;
      GamesPlayed = $resource("" + API_BASE + "userGames/played.json", {}, {
        send: {
          method: "POST"
        }
      });
      $send = GamesPlayed.send;
      GamesPlayed.send = function(game, success, error) {
        var send_data,
          _this = this;
        send_data = {
          idg: 1,
          idv: game.data.vid,
          pts: game.points,
          instance: game.data.instance,
          langdir: LANG_DIR,
          W: game.info || []
        };
        return $send(send_data, function(data) {
          if (isString(data.res)) {
            return success != null ? success.call(_this, data) : void 0;
          } else {
            return error != null ? error.call(_this, data) : void 0;
          }
        });
      };
      return GamesPlayed;
    };
    Console.groupEnd();
    return service;
  });

}).call(this);
