// Generated by CoffeeScript 1.3.3
(function() {

  define(["Console", "Underscore", "services/DiagnosticWordsService", "services/UserService", "services/GameWordsService", "services/ChallengeWordsService", "services/GamesService", "services/GamesPlayed"], function(Console, _, dws, us, gws, cws, gs, gp) {
    "use strict";
    Console.group("Entering Service module.");
    Console.info("DiagnosticWordsService", dws);
    Console.groupEnd();
    return function() {
      Console.debug("Custom services initialized.");
      return angular.module("uspeak.diagnostic.resources", ["ngResource"]).factory("DiagnosticWordsService", dws).factory("GameWordsService", gws).factory("ChallengeWordsService", cws).factory("UserService", us).factory("GamesService", gs).factory("GamesPlayed", gp).factory("user", function(UserService) {
        var user;
        user = new UserService();
        if (DEBUG) {
          user.setToken("testtoken");
        }
        return user;
      }).factory("games", function() {
        return new ((function() {

          function _Class() {}

          _Class.prototype.games = [];

          _Class.prototype.register = function(gameController, attrs) {
            gameController.id = parseInt(attrs.gameId);
            gameController.name = attrs.gameTitle;
            gameController.description = attrs.gameDescription;
            gameController.controller = attrs.gameController.toLowerCase();
            Console.info("Registered game " + gameController.name, gameController);
            return this.games.push(gameController);
          };

          _Class.prototype.get = function(key, value) {
            return _.find(this.games, function(obj) {
              return obj[key] === value;
            }) || {};
          };

          _Class.prototype.id = function(value) {
            return this.get("id", parseInt(value));
          };

          _Class.prototype.controller = function(value) {
            return this.get("controller", value);
          };

          return _Class;

        })())();
      });
    };
  });

}).call(this);
