// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  var i, loader_modules, module, _fn;

  loader.addModules(["Console", "jQuery", "jQuery-plugins", "SoundManager", "Underscore", "WebFont", "WebFont-fonts", "app", "Angular", "DOM"]);

  require.config({
    paths: {
      Console: "require/console",
      jQuery: "require/jquery",
      Underscore: "require/underscore",
      WebFont: "require/webfont",
      Angular: "require/angular",
      SoundManager: "require/soundmanager2"
    },
    priority: ["Console", "jQuery", "Underscore", "Angular", "WebFont", "SoundManager"],
    waitSeconds: 40,
    urlArgs: 'v=' + (DEBUG ? Math.random() : '2.0')
  });

  require(["require", "Console", "jQuery", "Underscore", "Angular"], function(require, Console, $, _, angular) {
    Console.group("Bootstrap dependencies loaded. Starting bootstrap.");
    Console.info("Console", Console);
    Console.info("jQuery", $);
    Console.info("Underscore: ", _);
    Console.info("Angular: ", angular);
    require(["app"], function(App) {
      loader.setLoaded("app");
      Console.group("Starting bootstrap.");
      Console.info("App: ", App);
      App();
      return Console.groupEnd();
    });
    return Console.groupEnd();
  });

  require(["jQuery"], function($) {
    var $id, bb, bubbles, bubbles_progress, game;
    game = $("#game");
    $(document).ready(function() {
      return loader.setLoaded("DOM");
    });
    if (!DEBUG) {
      bubbles = $("#game-loader-progress").children();
      bubbles_progress = 0;
      bb = bubbles.first();
      $id = setInterval(function() {
        bubbles_progress = (bubbles.index(bb) + 1) / bubbles.length;
        if (bubbles_progress > loader.loaded()) {
          return;
        }
        loader.loaded();
        bb.addClass("ld");
        bb = bb.next();
        if (bb.length === 0) {
          clearInterval($id);
          return setTimeout((function() {
            return game.addClass("loaded");
          }), 600);
        }
      }, 120);
    } else {
      game.addClass("loaded");
    }
    return require(["lib/jquery.transit", "lib/jquery.keyframe", "lib/jquery.cssanimation.min", "lib/jquery.tzineClock"], function() {
      return loader.setLoaded("jQuery-plugins");
    });
  });

  require(["SoundManager"], function(soundManager) {
    soundManager.setup({
      url: "/swf/",
      preferFlash: false,
      flashVersion: 8,
      allowScriptAccess: "sameDomain",
      onready: function() {
        return loader.setLoaded("SoundManager");
      },
      ontimeout: function() {
        return loader.setLoaded("SoundManager");
      }
    });
    return soundManager.beginDelayedInit();
  });

  require(["WebFont"], function(WebFont) {
    return WebFont.load({
      google: {
        families: ["Lato:400,900", "Delius", "Paytone One", "Lobster"]
      },
      typekit: {
        id: "geg8tlg"
      },
      active: function() {
        return loader.setLoaded("WebFont-fonts");
      },
      inactive: function() {
        return loader.setLoaded("WebFont-fonts");
      }
    });
  });

  loader_modules = ["Console", "jQuery", "Underscore", "WebFont", "Angular"];

  module = void 0;

  _fn = function(mod) {
    return require([mod], function() {
      return loader.setLoaded(mod);
    });
  };
  for (i in loader_modules) {
    module = loader_modules[i];
    _fn(module);
  }

}).call(this);
