// Generated by CoffeeScript 1.3.3
(function() {
  var Timer, TimerInterval, isString;

  Timer = function(callback, delay) {
    var remaining, start, timerId;
    timerId = void 0;
    start = void 0;
    remaining = delay;
    this.pause = function() {
      window.clearTimeout(timerId);
      return remaining -= new Date() - start;
    };
    this.resume = function() {
      start = new Date();
      return timerId = window.setTimeout(callback, remaining);
    };
    return this.resume();
  };

  TimerInterval = function(callback, delay) {
    var remaining, start, timerId;
    timerId = void 0;
    start = void 0;
    remaining = delay;
    this.pause = function() {
      window.clearInterval(timerId);
      return remaining -= new Date() - start;
    };
    this.resume = function() {
      start = new Date();
      return timerId = window.setInterval(callback, remaining);
    };
    return this.resume();
  };

  isString = function(o) {
    return typeof o === "string" || (typeof o === "object" && o.constructor === String);
  };

  window.asFunc = function(v) {
    return function() {
      return v;
    };
  };

}).call(this);
